package main

import "text/template"

// The generated type is GUARDED: its fields are unexported, so the only ways
// to change one are the constructor and the typed setters, and both refuse a
// value the schema rejects. That is the whole point of generating it — the
// tagged-struct API cannot stop `u.Age = -1`.
//
// Everything that touches the wire delegates to the engine against the
// embedded schema. There is deliberately no inlined writer here: ADR 0004 D6
// allows one only behind byte-for-byte differential gates, and the generated
// test below is written to BE that gate if anyone adds it later.
var codeTemplate = template.Must(template.New("code").Parse(`// Code generated by iogen. DO NOT EDIT.

package {{.Package}}

import (
	"sync"
{{range .Imports}}	"{{.}}"
{{end}}
	io "github.com/maniartech/InternetObject-go"
)

// {{.Type}}Schema is the schema this type was generated from, verbatim. It is
// the source of truth for both: regenerate rather than edit either.
const {{.Type}}Schema = ` + "`" + `{{.SchemaText}}` + "`" + `

var (
	{{.Recv}}SchemaOnce sync.Once
	{{.Recv}}SchemaVal  *io.Schema
	{{.Recv}}SchemaErr  error
)

// {{.Type}}SchemaOf compiles the embedded schema once and reuses it. A compiled
// schema is read-only and safe to share across goroutines.
func {{.Type}}SchemaOf() (*io.Schema, error) {
	{{.Recv}}SchemaOnce.Do(func() {
		{{.Recv}}SchemaVal, {{.Recv}}SchemaErr = io.ParseSchema({{.Type}}Schema)
	})
	return {{.Recv}}SchemaVal, {{.Recv}}SchemaErr
}

// {{.Type}} is a guarded Internet Object record. Its fields are unexported: a
// value of this type that exists is one the schema accepted, because the
// constructor and every setter validate before committing.
type {{.Type}} struct {
{{range .Fields}}	{{.Priv}} {{.GoType}}
{{end}}}

// {{.PrivType}}Plain is the exported twin the engine binds. The guarded fields are
// unexported precisely so nothing can write past validation, and the engine
// binds by reflection over exported fields — so every crossing goes through
// here. The io tags carry the member names; types and constraints come from
// the schema, which is the only authority.
type {{.PrivType}}Plain struct {
{{range .Fields}}	{{.Go}} {{.GoType}} ` + "`" + `io:"{{.Member}}"` + "`" + `
{{end}}}

func ({{.Recv}} *{{.Type}}) plain() {{.PrivType}}Plain {
	return {{.PrivType}}Plain{
{{range .Fields}}		{{.Go}}: {{$.Recv}}.{{.Priv}},
{{end}}	}
}

func ({{.Recv}} *{{.Type}}) adopt(src {{.PrivType}}Plain) {
{{range .Fields}}	{{$.Recv}}.{{.Priv}} = src.{{.Go}}
{{end}}}

// New{{.Type}} builds a {{.Type}} and returns an error if the schema rejects it.
func New{{.Type}}({{range $i, $f := .Fields}}{{if $i}}, {{end}}{{$f.Priv}} {{$f.GoType}}{{end}}) (*{{.Type}}, error) {
	{{.Recv}} := &{{.Type}}{
{{range .Fields}}		{{.Priv}}: {{.Priv}},
{{end}}	}
	if err := {{.Recv}}.Validate(); err != nil {
		return nil, err
	}
	return {{.Recv}}, nil
}
{{range .Fields}}
// {{.Go}} returns the {{.Member}} member.
func ({{$.Recv}} *{{$.Type}}) {{.Go}}() {{.GoType}} { return {{$.Recv}}.{{.Priv}} }

// Set{{.Go}} sets the {{.Member}} member, or returns the schema's own error and
// leaves the value untouched. The whole record is revalidated: a guarded type's
// invariant is that it is valid, not merely that each field was valid alone.
func ({{$.Recv}} *{{$.Type}}) Set{{.Go}}(v {{.GoType}}) error {
	prev := {{$.Recv}}.{{.Priv}}
	{{$.Recv}}.{{.Priv}} = v
	if err := {{$.Recv}}.Validate(); err != nil {
		{{$.Recv}}.{{.Priv}} = prev
		return err
	}
	return nil
}
{{end}}
// Validate checks the record against the embedded schema.
func ({{.Recv}} *{{.Type}}) Validate() error {
	s, err := {{.Type}}SchemaOf()
	if err != nil {
		return err
	}
	return io.ValidateWith({{.Recv}}.plain(), s)
}

// Marshal renders the record as Internet Object text, schema header included.
func ({{.Recv}} *{{.Type}}) Marshal() (string, error) {
	s, err := {{.Type}}SchemaOf()
	if err != nil {
		return "", err
	}
	return io.MarshalWith({{.Recv}}.plain(), s)
}

// Unmarshal parses text into the record. The value is replaced only if the
// text validates, so a failed Unmarshal leaves the record as it was.
func ({{.Recv}} *{{.Type}}) Unmarshal(text string) error {
	s, err := {{.Type}}SchemaOf()
	if err != nil {
		return err
	}
	var src {{.PrivType}}Plain
	if err := io.UnmarshalWith(text, &src, s); err != nil {
		return err
	}
	{{.Recv}}.adopt(src)
	return nil
}
`))

// The generated tests assert AGREEMENT WITH THE ENGINE, not invented
// expectations. They cannot know a value this schema accepts — constraints are
// arbitrary — so every property below is one that holds for any schema.
var testTemplate = template.Must(template.New("test").Parse(`// Code generated by iogen. DO NOT EDIT.

package {{.Package}}

import (
	"testing"

	io "github.com/maniartech/InternetObject-go"
)

// The embedded schema must compile. Everything else depends on it.
func Test{{.Type}}SchemaCompiles(t *testing.T) {
	s, err := {{.Type}}SchemaOf()
	if err != nil {
		t.Fatalf("embedded schema does not compile: %v", err)
	}
	if got := len(s.MemberNames()); got != {{len .Fields}} {
		t.Errorf("schema declares %d members, the generated type has {{len .Fields}}", got)
	}
}

// Validate must agree with the engine exactly — the generated method is a
// delegation, and this fails the moment someone gives it logic of its own.
func Test{{.Type}}ValidateDelegates(t *testing.T) {
	s, err := {{.Type}}SchemaOf()
	if err != nil {
		t.Fatal(err)
	}
	var {{.Recv}} {{.Type}}
	got, want := {{.Recv}}.Validate(), io.ValidateWith({{.Recv}}.plain(), s)
	if (got == nil) != (want == nil) {
		t.Fatalf("Validate() = %v, engine = %v", got, want)
	}
	if got != nil && got.Error() != want.Error() {
		t.Errorf("Validate() = %q, engine = %q", got, want)
	}
}

// Marshal must be byte-identical to the engine's own output for the same
// value. Today that is true by construction; ADR 0004 D6 permits an inlined
// writer ONLY behind a byte-for-byte gate, and this is that gate.
func Test{{.Type}}MarshalDelegates(t *testing.T) {
	s, err := {{.Type}}SchemaOf()
	if err != nil {
		t.Fatal(err)
	}
	var {{.Recv}} {{.Type}}
	got, gotErr := {{.Recv}}.Marshal()
	want, wantErr := io.MarshalWith({{.Recv}}.plain(), s)
	if (gotErr == nil) != (wantErr == nil) {
		t.Fatalf("Marshal() error = %v, engine = %v", gotErr, wantErr)
	}
	if gotErr == nil && got != want {
		t.Errorf("Marshal() = %q, engine = %q", got, want)
	}
}

// The guard must hold: a rejected setter leaves the value exactly as it was.
// Proven without inventing a valid value — whatever the zero value marshals
// to before a failed setter, it must marshal to after.
func Test{{.Type}}RejectedSetterRollsBack(t *testing.T) {
	var {{.Recv}} {{.Type}}
	before, beforeErr := {{.Recv}}.Marshal()
{{range .Fields}}
	if err := {{$.Recv}}.Set{{.Go}}({{$.Recv}}.{{.Go}}()); err != nil {
		// Setting a member to the value it already holds must fail only when
		// the record was already invalid — never because of the set itself.
		if {{$.Recv}}.Validate() == nil {
			t.Errorf("Set{{.Go}}(current) failed on a valid record: %v", err)
		}
	}
{{end}}
	after, afterErr := {{$.Recv}}.Marshal()
	if (beforeErr == nil) != (afterErr == nil) || before != after {
		t.Errorf("setting members to their own values changed the record:\n before %q (%v)\n after  %q (%v)",
			before, beforeErr, after, afterErr)
	}
}

// Whatever this type marshals must read back as the same value.
//
// Both branches assert: this test never skips. A generated schema may reject
// the zero value — that is what a guarded type is FOR — and in that case the
// available property is that Marshal and Validate agree about it.
func Test{{.Type}}RoundTrips(t *testing.T) {
	var {{.Recv}} {{.Type}}
	text, err := {{.Recv}}.Marshal()
	if err != nil {
		if {{.Recv}}.Validate() == nil {
			t.Fatalf("Marshal failed (%v) on a record Validate accepts", err)
		}
		return
	}
	var back {{.Type}}
	if err := back.Unmarshal(text); err != nil {
		t.Fatalf("Unmarshal(%q) = %v", text, err)
	}
	again, err := back.Marshal()
	if err != nil {
		t.Fatal(err)
	}
	if again != text {
		t.Errorf("round trip changed the text:\n first %q\n again %q", text, again)
	}
}
`))
