// Code generated by iogen. DO NOT EDIT.
//
// iogen is EXPERIMENTAL: it currently generates a single record against a single
// schema, and will grow to cover collections and multi-section documents. The
// shape of this file may change with it, so regenerate rather than hand-edit.
// The library API this delegates to is stable; the generated surface is not.

package main

import (
	"sync"

	io "github.com/maniartech/InternetObject-go"
)

// PersonSchema is the schema this type was generated from, verbatim. It is
// the source of truth for both: regenerate rather than edit either.
const PersonSchema = `name: {string, minLen: 2, maxLen: 50}, age: {int, min: 0, max: 130}, email: string, active: bool, score: number, tags: [string]`

var (
	personSchemaOnce sync.Once
	personSchemaVal  *io.Schema
	personSchemaErr  error
)

// PersonSchemaOf compiles the embedded schema once and reuses it. A compiled
// schema is read-only and safe to share across goroutines.
func PersonSchemaOf() (*io.Schema, error) {
	personSchemaOnce.Do(func() {
		personSchemaVal, personSchemaErr = io.ParseSchema(PersonSchema)
	})
	return personSchemaVal, personSchemaErr
}

// Person is a guarded Internet Object record. Its fields are unexported: a
// value of this type that exists is one the schema accepted, because the
// constructor and every setter validate before committing.
type Person struct {
	name   string
	age    int
	email  string
	active bool
	score  float64
	tags   []string
}

// personPlain is the exported twin the engine binds. The guarded fields are
// unexported precisely so nothing can write past validation, and the engine
// binds by reflection over exported fields — so every crossing goes through
// here. The io tags carry the member names; types and constraints come from
// the schema, which is the only authority.
type personPlain struct {
	Name   string   `io:"name"`
	Age    int      `io:"age"`
	Email  string   `io:"email"`
	Active bool     `io:"active"`
	Score  float64  `io:"score"`
	Tags   []string `io:"tags"`
}

func (p *Person) plain() personPlain {
	return personPlain{
		Name:   p.name,
		Age:    p.age,
		Email:  p.email,
		Active: p.active,
		Score:  p.score,
		Tags:   p.tags,
	}
}

func (p *Person) adopt(src personPlain) {
	p.name = src.Name
	p.age = src.Age
	p.email = src.Email
	p.active = src.Active
	p.score = src.Score
	p.tags = src.Tags
}

// NewPerson builds a Person and returns an error if the schema rejects it.
func NewPerson(name string, age int, email string, active bool, score float64, tags []string) (*Person, error) {
	out := &Person{
		name:   name,
		age:    age,
		email:  email,
		active: active,
		score:  score,
		tags:   tags,
	}
	if err := out.Validate(); err != nil {
		return nil, err
	}
	return out, nil
}

// Name returns the name member.
func (p *Person) Name() string { return p.name }

// SetName sets the name member, or returns the schema's own error and
// leaves the value untouched. The whole record is revalidated: a guarded type's
// invariant is that it is valid, not merely that each field was valid alone.
func (p *Person) SetName(v string) error {
	prev := p.name
	p.name = v
	if err := p.Validate(); err != nil {
		p.name = prev
		return err
	}
	return nil
}

// Age returns the age member.
func (p *Person) Age() int { return p.age }

// SetAge sets the age member, or returns the schema's own error and
// leaves the value untouched. The whole record is revalidated: a guarded type's
// invariant is that it is valid, not merely that each field was valid alone.
func (p *Person) SetAge(v int) error {
	prev := p.age
	p.age = v
	if err := p.Validate(); err != nil {
		p.age = prev
		return err
	}
	return nil
}

// Email returns the email member.
func (p *Person) Email() string { return p.email }

// SetEmail sets the email member, or returns the schema's own error and
// leaves the value untouched. The whole record is revalidated: a guarded type's
// invariant is that it is valid, not merely that each field was valid alone.
func (p *Person) SetEmail(v string) error {
	prev := p.email
	p.email = v
	if err := p.Validate(); err != nil {
		p.email = prev
		return err
	}
	return nil
}

// Active returns the active member.
func (p *Person) Active() bool { return p.active }

// SetActive sets the active member, or returns the schema's own error and
// leaves the value untouched. The whole record is revalidated: a guarded type's
// invariant is that it is valid, not merely that each field was valid alone.
func (p *Person) SetActive(v bool) error {
	prev := p.active
	p.active = v
	if err := p.Validate(); err != nil {
		p.active = prev
		return err
	}
	return nil
}

// Score returns the score member.
func (p *Person) Score() float64 { return p.score }

// SetScore sets the score member, or returns the schema's own error and
// leaves the value untouched. The whole record is revalidated: a guarded type's
// invariant is that it is valid, not merely that each field was valid alone.
func (p *Person) SetScore(v float64) error {
	prev := p.score
	p.score = v
	if err := p.Validate(); err != nil {
		p.score = prev
		return err
	}
	return nil
}

// Tags returns the tags member.
func (p *Person) Tags() []string { return p.tags }

// SetTags sets the tags member, or returns the schema's own error and
// leaves the value untouched. The whole record is revalidated: a guarded type's
// invariant is that it is valid, not merely that each field was valid alone.
func (p *Person) SetTags(v []string) error {
	prev := p.tags
	p.tags = v
	if err := p.Validate(); err != nil {
		p.tags = prev
		return err
	}
	return nil
}

// Validate checks the record against the embedded schema.
func (p *Person) Validate() error {
	s, err := PersonSchemaOf()
	if err != nil {
		return err
	}
	return io.ValidateWith(p.plain(), s)
}

// Marshal renders the record as Internet Object text, schema header included.
func (p *Person) Marshal() (string, error) {
	s, err := PersonSchemaOf()
	if err != nil {
		return "", err
	}
	return io.MarshalWith(p.plain(), s)
}

// Unmarshal parses text into the record. The value is replaced only if the
// text validates, so a failed Unmarshal leaves the record as it was.
func (p *Person) Unmarshal(text string) error {
	s, err := PersonSchemaOf()
	if err != nil {
		return err
	}
	var src personPlain
	if err := io.UnmarshalWith(text, &src, s); err != nil {
		return err
	}
	p.adopt(src)
	return nil
}
