// Code generated by iogen. DO NOT EDIT.

package main

import (
	"testing"

	io "github.com/maniartech/InternetObject-go"
)

// The embedded schema must compile. Everything else depends on it.
func TestPersonSchemaCompiles(t *testing.T) {
	s, err := PersonSchemaOf()
	if err != nil {
		t.Fatalf("embedded schema does not compile: %v", err)
	}
	if got := len(s.MemberNames()); got != 6 {
		t.Errorf("schema declares %d members, the generated type has 6", got)
	}
}

// Validate must agree with the engine exactly — the generated method is a
// delegation, and this fails the moment someone gives it logic of its own.
func TestPersonValidateDelegates(t *testing.T) {
	s, err := PersonSchemaOf()
	if err != nil {
		t.Fatal(err)
	}
	var p Person
	got, want := p.Validate(), io.ValidateWith(p.plain(), s)
	if (got == nil) != (want == nil) {
		t.Fatalf("Validate() = %v, engine = %v", got, want)
	}
	if got != nil && got.Error() != want.Error() {
		t.Errorf("Validate() = %q, engine = %q", got, want)
	}
}

// Marshal must be byte-identical to the engine's own output for the same
// value. Today that is true by construction; ADR 0004 D6 permits an inlined
// writer ONLY behind a byte-for-byte gate, and this is that gate.
func TestPersonMarshalDelegates(t *testing.T) {
	s, err := PersonSchemaOf()
	if err != nil {
		t.Fatal(err)
	}
	var p Person
	got, gotErr := p.Marshal()
	want, wantErr := io.MarshalWith(p.plain(), s)
	if (gotErr == nil) != (wantErr == nil) {
		t.Fatalf("Marshal() error = %v, engine = %v", gotErr, wantErr)
	}
	if gotErr == nil && got != want {
		t.Errorf("Marshal() = %q, engine = %q", got, want)
	}
}

// The guard must hold: a rejected setter leaves the value exactly as it was.
// Proven without inventing a valid value — whatever the zero value marshals
// to before a failed setter, it must marshal to after.
func TestPersonRejectedSetterRollsBack(t *testing.T) {
	var p Person
	before, beforeErr := p.Marshal()

	if err := p.SetName(p.Name()); err != nil {
		// Setting a member to the value it already holds must fail only when
		// the record was already invalid — never because of the set itself.
		if p.Validate() == nil {
			t.Errorf("SetName(current) failed on a valid record: %v", err)
		}
	}

	if err := p.SetAge(p.Age()); err != nil {
		// Setting a member to the value it already holds must fail only when
		// the record was already invalid — never because of the set itself.
		if p.Validate() == nil {
			t.Errorf("SetAge(current) failed on a valid record: %v", err)
		}
	}

	if err := p.SetEmail(p.Email()); err != nil {
		// Setting a member to the value it already holds must fail only when
		// the record was already invalid — never because of the set itself.
		if p.Validate() == nil {
			t.Errorf("SetEmail(current) failed on a valid record: %v", err)
		}
	}

	if err := p.SetActive(p.Active()); err != nil {
		// Setting a member to the value it already holds must fail only when
		// the record was already invalid — never because of the set itself.
		if p.Validate() == nil {
			t.Errorf("SetActive(current) failed on a valid record: %v", err)
		}
	}

	if err := p.SetScore(p.Score()); err != nil {
		// Setting a member to the value it already holds must fail only when
		// the record was already invalid — never because of the set itself.
		if p.Validate() == nil {
			t.Errorf("SetScore(current) failed on a valid record: %v", err)
		}
	}

	if err := p.SetTags(p.Tags()); err != nil {
		// Setting a member to the value it already holds must fail only when
		// the record was already invalid — never because of the set itself.
		if p.Validate() == nil {
			t.Errorf("SetTags(current) failed on a valid record: %v", err)
		}
	}

	after, afterErr := p.Marshal()
	if (beforeErr == nil) != (afterErr == nil) || before != after {
		t.Errorf("setting members to their own values changed the record:\n before %q (%v)\n after  %q (%v)",
			before, beforeErr, after, afterErr)
	}
}

// Whatever this type marshals must read back as the same value.
//
// Both branches assert: this test never skips. A generated schema may reject
// the zero value — that is what a guarded type is FOR — and in that case the
// available property is that Marshal and Validate agree about it.
func TestPersonRoundTrips(t *testing.T) {
	var p Person
	text, err := p.Marshal()
	if err != nil {
		if p.Validate() == nil {
			t.Fatalf("Marshal failed (%v) on a record Validate accepts", err)
		}
		return
	}
	var back Person
	if err := back.Unmarshal(text); err != nil {
		t.Fatalf("Unmarshal(%q) = %v", text, err)
	}
	again, err := back.Marshal()
	if err != nil {
		t.Fatal(err)
	}
	if again != text {
		t.Errorf("round trip changed the text:\n first %q\n again %q", text, again)
	}
}
